# ABOUTME: Woodpecker CI job for implementing a single issue
# Triggered when ai:ready label is added to a Linear Issue

when:
  - event: custom
    # Triggered by Linear webhook when ai:ready label is added to an Issue

steps:
  checkout:
    image: alpine/git:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      # Clone the repository
      - git clone https://${GITHUB_TOKEN}@github.com/${CI_REPO}.git /workspace
      - cd /workspace && git checkout main && git pull origin main

  implement:
    image: anthropic/claude-code:latest
    environment:
      LINEAR_TOKEN:
        from_secret: linear_token
      ANTHROPIC_API_KEY:
        from_secret: anthropic_api_key
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - cd /workspace

      # Parse webhook payload for Issue ID/identifier
      - export ISSUE_ID=$(echo "$CI_CUSTOM_PAYLOAD" | jq -r '.data.id // .issueId // empty')
      - export ISSUE_IDENTIFIER=$(echo "$CI_CUSTOM_PAYLOAD" | jq -r '.data.identifier // empty')

      # Validate Issue ID was extracted
      - |
        if [ -z "$ISSUE_ID" ] && [ -z "$ISSUE_IDENTIFIER" ]; then
          echo "Error: Could not extract Issue ID from webhook payload"
          exit 1
        fi

      # Use identifier if available, otherwise use ID
      - export ISSUE_REF=${ISSUE_IDENTIFIER:-$ISSUE_ID}

      # Configure git for commits
      - git config user.name "Claude Code Bot"
      - git config user.email "claude-bot@example.com"

      # Run the implementation command
      - |
        claude --dangerously-skip-permissions \
          "/speckit.implement $ISSUE_REF" \
          --output-format json > /tmp/implement-result.json 2>&1 || true

      # Check result and handle accordingly
      - |
        if grep -q '"status": "blocked"' /tmp/implement-result.json; then
          echo "Implementation blocked - waiting for blockers to complete"
          exit 0
        elif grep -q '"status": "retry"' /tmp/implement-result.json; then
          echo "Implementation failed - retry scheduled"
          exit 0
        elif grep -q '"status": "success"' /tmp/implement-result.json; then
          echo "Implementation completed successfully"
          cat /tmp/implement-result.json | jq '.pr_url // .summary // .'
          exit 0
        else
          echo "Implementation failed unexpectedly"
          cat /tmp/implement-result.json
          exit 1
        fi

  notify-failure:
    image: curlimages/curl:latest
    when:
      - status: failure
    environment:
      LINEAR_TOKEN:
        from_secret: linear_token
    commands:
      - export ISSUE_ID=$(echo "$CI_CUSTOM_PAYLOAD" | jq -r '.data.id // .issueId // empty')
      - |
        curl -X POST https://api.linear.app/graphql \
          -H "Authorization: $LINEAR_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"query\": \"mutation { commentCreate(input: { issueId: \\\"$ISSUE_ID\\\", body: \\\"CI: Implementation job failed unexpectedly. Check Woodpecker logs for details.\\\" }) { comment { id } } }\"
          }"
      - |
        # Add ai:blocked label
        curl -X POST https://api.linear.app/graphql \
          -H "Authorization: $LINEAR_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"query\": \"mutation { issueUpdate(id: \\\"$ISSUE_ID\\\", input: { labelIds: [\\\"$AI_BLOCKED_LABEL_ID\\\"] }) { issue { id } } }\"
          }"
